import Head from 'next/head'
import Navbar from '../components/navbar.tsx'
import Hero from '../components/hero.tsx'
import Footer from '../components/footer.tsx'
import Features from '../components/feature.tsx'

export default function Home() {
  return (
    <>
      <Head>
        <title>givitoo.me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero />
        <Features />
      </main>

      <Footer />
    </>
  )
}
